theme="cocoa"
languageCode = "en-us"
title = "Learning Rust: Make a Redis Proxy"
baseurl = "http://example.org/"
builddrafts = true
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Arthur Dent"
pygmentsuseclasses  = true
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author       = "Learning Rust: Make a Redis Proxy"
cachebuster  = true # add the current unix timestamp in query string for cache busting css assets
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "Don't panic"
email        = "you@example.space"
faviconfile  = "img/leaf.ico"
github       = "//github.com/you"
highlightjs  = true
lang         = "en"
linkedin     = "//linkedin.com/in/you"
twitter      = "//twitter.com/you"
selfIntro    = "" # appears in the site header when set to a non-empty string
extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.
